# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48c7a9659b99f92f0be1aa38259cc77694507fb6685eed62cf87bacd660ef428b6c09f36b14f0fae8b92a5237b886204c223b52a4e98cbc3e0349c864ff1f010

test:
  secret_key_base: f56b2d7efcccffdbd2918ed78d1d5afdaf881e0e8c2b86d176abb74f300b36a5105b49d5cc74e54e586c52fb0d6a5b60e973faabcca120e078a8489c4f3a7bb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
